### ISSUE TITLE
(node:11012) UnhandledPromiseRejectionWarning: TypeError: name.orig.at is not a function

### ISSUE THREAD

**Issue by nurikk** [pirxpilot/connect-gzip-static#16]
Hello, after update to v3.0 we started to receive errors like this:

```
(node:11012) UnhandledPromiseRejectionWarning: TypeError: name.orig.at is not a function
    at check (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:94:19)
    at Frontend.gzipStatic (/opt/zigbee2mqtt/node_modules/connect-gzip-static/lib/gzip-static.js:54:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by pirxpilot** [comment]
`String.prototype.at` is [fairly new][1] but supported by by active LTS version.

[1]: https://node.green/#ES2022-features--at---method-on-the-built-in-indexables-String-prototype-at--
